imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
        grouped:
            type: group
            members: [nested, mail]
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
        mail:
            type: fingers_crossed
            action_level: error
            handler: deduplicated
        deduplicated:
            type: deduplication
            handler: swift
        swift:
            type: swift_mailer
            from_email: 'qiv@upactivity.com'
            to_email: 'qiv@upactivity.com'
            subject: '%%message%%'
            level: debug
            content_type: text/html
